Service/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    #Hospitals
    path("view/hospitals",views.viewhospitals,name = "view_all_hospitals"),
    path("add/hospital",views.AddHospitalView.as_view(),name = "add_hospital"),
    path("update/<int:pk>/<slug:slug>/hospital",views.UpdateHospitalView.as_view(),name = "update_hospital_details"),
    path("delete/<int:pk>/<slug:slug>/hospital/profile",views.deletehospital,name = "delete_hospital_profile"),
    #Doctors
    path("view/doctors",views.viewdoctors,name = "view_all_doctors"),
    path("add/doctor",views.AddDoctorView.as_view(),name = "add_doctor"),
    path("update/<int:pk>/<slug:slug>/doctor",views.UpdateDoctorView.as_view(),name = "update_doctor_details"),
    path("delete/<int:pk>/<slug:slug>/doctor/profile",views.deletedoctor,name = "delete_doctor_profile"),
    path("view/<int:pk>/doctors/<slug:slug>/related/hospital",views.doctorsrelatedtohospital,name = "view_doctors_realted_to_hospital"),
]

content_manager/urls.py
from Service import views
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name = "home"),
    path('service/',include("Service.urls"))
]
urlpatterns+=static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

Service/models.py
from django.db import models
from django_countries.fields import CountryField
from autoslug import AutoSlugField
# Create your models here.
class Hospital(models.Model):
    Hospital_Name = models.CharField(max_length = 200)
    Hospital_Code = models.PositiveIntegerField()
    Location = CountryField()
    slug = AutoSlugField(populate_from ="Hospital_Name",unique = True)
    def __str__(self):
        return str(self.Hospital_Name)+'-'+str(self.Hospital_Code)
class Doctor(models.Model):
    Doctor_Id = models.PositiveBigIntegerField()
    Doctor_Name = models.CharField(max_length = 45)
    Profile_Picture = models.ImageField(upload_to='profile/',blank = True)
    Date_of_Joining = models.DateField()
    Qualification = models.CharField(max_length = 200)
    Specialization = models.CharField(max_length = 300,blank = True)
    slug = AutoSlugField(populate_from = "Doctor_Name",unique = True)
    Hospital = models.ForeignKey(Hospital,on_delete = models.CASCADE)
    def __str__(self):
        return 'Dr. '+str(self.Doctor_Name)+'-'+str(self.Qualification)        
    

Service/views.py
from .models import Hospital,Doctor
from .filters import HospitalFilter,DoctorFilter
from django import forms
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.shortcuts import render,redirect
from django.views import generic
from django.urls import reverse_lazy,reverse
from django.db.models import Count


# Create your views here.
#Class Based Views
#Hospitals
class AddHospitalView(SuccessMessageMixin,generic.CreateView):
    model = Hospital
    fields = ['Hospital_Name','Hospital_Code','Location']
    template_name = "Service/Hospital/AddHospital.html"
    success_url = reverse_lazy("view_all_hospitals")
    success_message = "Added Hospital successfully"
    def form_valid(self,form):
        return super().form_valid(form)
class UpdateHospitalView(generic.UpdateView):
    model = Hospital
    fields = ['Hospital_Name','Hospital_Code','Location']
    slug_field = Hospital.slug
    template_name = "Service/Hospital/UpdateHospitalDetails.html"
    def get_success_url(self):
        pk = self.kwargs["pk"]
        slug = self.kwargs["slug"]
        messages.success(self.request,'Updated Successfully')
        return reverse("update_hospital_details", kwargs={"pk": pk,'slug':slug})
#Doctors
class AddDoctorView(SuccessMessageMixin,generic.CreateView):
    model = Doctor
    fields = ["Doctor_Name","Doctor_Id","Profile_Picture","Date_of_Joining","Qualification","Specialization","Hospital"]   
    template_name = "Service/Doctor/AddDoctor.html"
    success_url = reverse_lazy("view_all_doctors")
    success_message = "Added Doctor successfully"
    def get_form(self, form_class=None):
        form = super(AddDoctorView, self).get_form(form_class)
        form.fields['Date_of_Joining'].widget = forms.DateInput(format='%d/%m/%Y')
        return form
    def form_valid(self,form):
        return super().form_valid(form)
class UpdateDoctorView(generic.UpdateView):
    model = Doctor
    fields = ["Doctor_Name","Doctor_Id","Profile_Picture","Date_of_Joining","Qualification","Specialization","Hospital"] 
    slug_field = Doctor.slug
    template_name = "Service/Doctor/UpdateDoctorDetails.html"
    def get_success_url(self):
        pk = self.kwargs["pk"]
        slug = self.kwargs["slug"]
        messages.success(self.request,'Updated Successfully')
        return reverse("update_doctor_details", kwargs={"pk": pk,'slug':slug})
    
#Function Based Views
def home(request):
    return render(request,"Service/home.html")
def viewhospitals(request):
    hospital_list = Hospital.objects.order_by("Hospital_Code").all()
    hospital_filter = HospitalFilter(request.GET, queryset=hospital_list)
    return render(request, 'Service/Hospital/viewhospitals.html', {'Hospitals': hospital_filter,})
def viewdoctors(request):
    doctors = Doctor.objects.prefetch_related("Hospital").order_by("-Date_of_Joining").all()
    doctor_filter = DoctorFilter(request.GET)
    return render(request,"Service/Doctor/viewdoctors.html",{"Doctors":doctor_filter})
def deletedoctor(request,pk,slug):
    Doctor_Profile = Doctor.objects.prefetch_related("Hospital").get(id = pk,slug = slug)
    if request.method == "POST":
        Doctor_Profile.delete()
        messages.success(request,"Deleted Doctor Profile successfully")
        return redirect("view_all_doctors")
def deletehospital(request,pk,slug):
    Hospital_Profile = Hospital.objects.get(id = pk,slug = slug)
    if request.method == "POST":
        Hospital_Profile.delete()
        messages.success(request,"Deleted Hospital Profile successfully")
        return redirect("view_all_hospitals")
def doctorsrelatedtohospital(request,pk,slug):
    Hospital_Profile = Hospital.objects.get(id = pk,slug = slug)
    doctors = Doctor.objects.prefetch_related("Hospital").filter(Hospital = Hospital_Profile).order_by("-Date_of_Joining")
    return render(request,"Service/relateddoctors.html",{"Doctors":doctors,"Hospital":Hospital_Profile})
    

Service/templates/Service/Doctor/AddDoctor.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class = "container">
    <h1 class = "text-center">Add Doctor</h1>
    <hr/>
    <form method = "POST" enctype = "multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <div class = "d-inline-block py-2">
            <button class="btn btn-primary" type="submit" style="background: linear-gradient(43deg, #405de6 0%, #5851d8 17%, #833ab4 37%, #c13584 49%, #e1306c 72%, #e1306c 88%, #ee8bac 97%, #ffdc80 100%), var(--bs-red);"><i class = "fa fa-plus" ></i> Add Doctor</button>
        </div>
    </form>
</div>
<script>
    $(function () {
      $("#id_Date_of_Joining").datepicker({
        format:'dd/mm/yyyy',
      });
    });
  </script>
{% endblock %}

Service/templates/Service/Doctor/UpdateDoctorDetails.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class = "container">
    <h1 class = "text-center">Update Doctor</h1>
    <hr/>
    <form method = "POST" enctype = "multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <div class = "d-inline-block py-2">
            <button class="btn btn-outline-success" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none">
                <path d="M4 16L4 17C4 18.6569 5.34315 20 7 20L17 20C18.6569 20 20 18.6569 20 17L20 16M16 8L12 4M12 4L8 8M12 4L12 16" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
            </svg>&nbsp;Update Doctor Details</button>
            <a href = "{% url 'view_all_hospitals' %}" class="btn btn-outline-primary" type="button"><i
        class="fa fa-long-arrow-left"></i>&nbsp;Go Back</a>
        </div>
    </form>
</div>
<script>
    $(function () {
      $("#id_Date_of_Joining").datepicker({
        format:'dd/mm/yyyy',
      });
    });
  </script>
{% endblock %}

Service/templates/Service/Doctor/viewdoctors.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class = "container">
    <h1 class = "text-center">View Doctors</h1>
    <hr/>
    <div class = "container" style = "margin-bottom:10px;">
        <form method = "GET">
            <div class = "row">
                <div class = "col-md-2">
                    {{Doctors.form.Doctor_Name|as_crispy_field}}
                </div>
                <div class = "col-md-2">
                    {{Doctors.form.Hospital|as_crispy_field}}
                </div>
                <div class = "col-md-2">
                    {{Doctors.form.Qualification|as_crispy_field}}
                </div>
                <div class = "col-md-2">
                    {{Doctors.form.Date_of_Joining|as_crispy_field}}
                </div>
                <div class = "col-md-2">
                    {{Doctors.form.Specialization|as_crispy_field}}
                </div>
                <div class = "col-md-2">
                    <button class="btn btn-primary" data-bss-hover-animate="pulse" type="submit"
            style="text-align: center;margin-top:20px;background: linear-gradient(43deg, #405de6 0%, #5851d8 17%, #833ab4 37%, #c13584 49%, #e1306c 72%, #e1306c 88%, #ee8bac 97%, #ffdc80 100%), var(--bs-red);"><i
                class="fa fa-search"></i> Search</button>
                </div>
            </div>
        </form>
    </div>
    <hr/>
    <div class="row">
        {% for doctor in Doctors.qs %}
        <div class="col-md-4" style = "margin-bottom:10px;">
            <div class="card" style="width: auto;">
                {% if doctor.Profile_Picture %}
                    <img src="{{doctor.Profile_Picture.url}}" class="card-img-top" alt="{% static 'default.png' %}">
                {% else %}
                    <img src="{% static 'default.png' %}" class="card-img-top" alt="{% static 'default.png' %}">
                {% endif %}
                <div class="card-body">
                    <h1 class="card-subtitle mb-2 doctor-text ">Name : Dr. {{doctor.Doctor_Name}}</h1>
                    <h1 class="card-subtitle mb-2 doctor-text ">ID : {{doctor.Doctor_Id}}</h1>
                    <h1 class = "doctor-text">Qualification : {{doctor.Qualification}}</h1>
                    <h1 class = "doctor-text">Specialization: {% if doctor.Specialization %} {{doctor.Specialization}} {% else %}-{% endif %}</h1>
                    <h1 class = "doctor-text">Date of Joining : {{doctor.Date_of_Joining}}</h1>
                    <h1 class = "doctor-text">Hospital : {{doctor.Hospital.Hospital_Name}}</h1>
                    <h1 class = "doctor-text">Hospital Code : {{doctor.Hospital.Hospital_Code}}</h1>
                    <h1 class = "doctor-text">Hospital Location : <i class="{{ doctor.Hospital.Location.flag_css }}"></i> {{doctor.Hospital.Location.name}}</h1>
                    <div class = "d-inline-block py-2">
                        <form method = "POST" action = "{% url 'delete_doctor_profile' doctor.id doctor.slug %}">
                        <a class="btn btn-outline-success" href = "{% url 'update_doctor_details' doctor.id doctor.slug %}"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none">
                                <path d="M4 16L4 17C4 18.6569 5.34315 20 7 20L17 20C18.6569 20 20 18.6569 20 17L20 16M16 8L12 4M12 4L8 8M12 4L12 16" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                            </svg>&nbsp;Update
                        </a>
                            {% csrf_token %}
                            <button type = "submit" class="btn btn-outline-danger">
                                <i class="icon ion-android-delete"></i>&nbsp;Delete
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class = "d-inline-block">
        <a class="btn btn-primary" href = "{% url 'add_doctor' %}" style="background: linear-gradient(43deg, #405de6 0%, #5851d8 17%, #833ab4 37%, #c13584 49%, #e1306c 72%, #e1306c 88%, #ee8bac 97%, #ffdc80 100%), var(--bs-red);"><i class = "fa fa-plus"></i> Add a Doctor</a>
    </div>
</div>
{% endblock %}

Service/templates/Service/Hospital/AddHospital.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class = "container">
    <h1 class = "text-center">Add Hospital</h1>
    <hr/>
    <form method = "POST" enctype = "multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <div class = "d-inline-block py-2">
            <button class="btn btn-primary" type="submit" style="background: linear-gradient(43deg, #405de6 0%, #5851d8 17%, #833ab4 37%, #c13584 49%, #e1306c 72%, #e1306c 88%, #ee8bac 97%, #ffdc80 100%), var(--bs-red);"><i class = "fa fa-plus" ></i> Add Hospital</button>
        </div>
    </form>
</div>
{% endblock %}

Service/templates/Service/Hospital/UpdateHospitalDetails.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class = "container">
    <h1 class = "text-center">Update Doctor</h1>
    <hr/>
    <form method = "POST" enctype = "multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <div class = "d-inline-block py-2">
          <button class="btn btn-outline-success" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none">
            <path d="M4 16L4 17C4 18.6569 5.34315 20 7 20L17 20C18.6569 20 20 18.6569 20 17L20 16M16 8L12 4M12 4L8 8M12 4L12 16" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
        </svg>&nbsp;Update Hospital Details</button>
            <a href = "{% url 'view_all_doctors' %}" class="btn btn-outline-primary" type="button"><i
        class="fa fa-long-arrow-left"></i>&nbsp;Go Back</a>
        </div>
    </form>
</div>
<script>
    $(function () {
      $("#id_Date_of_Joining").datepicker({
        format:'dd/mm/yyyy',
      });
    });
  </script>
{% endblock %}

Service/templates/Service/Hospital/viewhospitals.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class = "container">
    <h1 class = "text-center">View Hospitals</h1>
    <hr/>
    <div class = "container" style = "margin-bottom:10px;">
        <form method = "GET">
            <div class = "row">
                <div class = "col-md-3">
                    {{Hospitals.form.Hospital_Name|as_crispy_field}}
                </div>
                <div class = "col-md-3">
                    {{Hospitals.form.Hospital_Code|as_crispy_field}}
                </div>
                <div class = "col-md-3">
                    {{Hospitals.form.Location|as_crispy_field}}
                </div>
                <div class = "col-md-3">
                    <button class="btn btn-primary" data-bss-hover-animate="pulse" type="submit"
            style="text-align: center;margin-top:20px;background: linear-gradient(43deg, #405de6 0%, #5851d8 17%, #833ab4 37%, #c13584 49%, #e1306c 72%, #e1306c 88%, #ee8bac 97%, #ffdc80 100%), var(--bs-red);"><i
                class="fa fa-search"></i> Search</button>
                </div>
            </div>
        </form>
    </div>
    <hr/>
    <div class="row">
        {% for hospital in Hospitals.qs %}
        <div class="col-md-4" style = "margin-bottom:10px;">
            <div class="card" >
                <div class="card-body"><img>
                    <h1 class="card-subtitle mb-2" style="font-size: 20px;">Name : {{hospital.Hospital_Name}}</h1>
                    <h1 style="font-size: 18px;">Code : {{hospital.Hospital_Code}}</h1>
                    <h1 style="font-size: 18px;">Location : <i class="{{ hospital.Location.flag_css }}"></i> {{hospital.Location.name}}</h1>
                    <div class = "d-inline-block py-2">
                        <form method = "POST" action = "{% url 'delete_hospital_profile' hospital.id hospital.slug %}" class = "py-2">
                            <a class="btn btn-outline-success "style = "margin-bottom:10px;" href = "{% url 'update_hospital_details' hospital.id hospital.slug %}"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none">
                                    <path d="M4 16L4 17C4 18.6569 5.34315 20 7 20L17 20C18.6569 20 20 18.6569 20 17L20 16M16 8L12 4M12 4L8 8M12 4L12 16" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                                </svg>&nbsp;Update
                            </a>
                                {% csrf_token %}
                                <button type = "submit" class="btn btn-outline-danger" style = "margin-bottom:10px;">
                                    <i class="icon ion-android-delete"></i>&nbsp;Delete
                                </button>
                                <a class="btn btn-outline-success" style = "margin-bottom:10px;" href = "{% url 'view_doctors_realted_to_hospital' hospital.id hospital.slug %}"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none">
                                    <path d="M4 16L4 17C4 18.6569 5.34315 20 7 20L17 20C18.6569 20 20 18.6569 20 17L20 16M16 8L12 4M12 4L8 8M12 4L12 16" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                                </svg>&nbsp;View Doctor Details
                            </a>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class = "d-inline-block">
        <a class="btn btn-primary" href = "{% url 'add_hospital' %}" style="background: linear-gradient(43deg, #405de6 0%, #5851d8 17%, #833ab4 37%, #c13584 49%, #e1306c 72%, #e1306c 88%, #ee8bac 97%, #ffdc80 100%), var(--bs-red);"><i class = "fa fa-plus"></i> Add a Hospital</a>
    </div>
</div>
{% endblock %}

Service/templates/Service/home.html
{% extends 'base.html' %}
{% block content %}
<div class = "container">
    <div class = "row" style = "margin-top:100px;">
        <div class = "col-md-6">
            <article>
                <section class="article-clean">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2">
                                <div class="intro">
                                    <h1 class="text-center">Hospital Management System</h1>
                                    <p class="text-center"><span class="by">by </span>Shyam Sundhar<span class="date text-muted"> HAWC Backend Assignment</span></p>
                                </div>
                                <div class="text">
                                    <p>This Project is done for illustration of Concept of Relation Database as mentioned in the Assignment. Since, it was asked for a basic project, I haven't included any authentication services. So, this is project is basically a content manager for hospital with CRUD Functionalities. Any User Can View the hospitals,doctors and can do the RUD functionalities for the same .</p>
                                    <div class = "d-inline-block py-2">
                                        <a class = "btn btn-primary" data-bss-hover-animate="pulse" style="background: linear-gradient(43deg, #405de6 0%, #5851d8 17%, #833ab4 37%, #c13584 49%, #e1306c 72%, #e1306c 88%, #ee8bac 97%, #ffdc80 100%), var(--bs-red);margin-right:10px;margin-bottom:10px;" href = "{% url 'view_all_hospitals' %}">Hospital Manager</a>
                                        <a class = "btn btn-primary" data-bss-hover-animate="pulse" style="background: linear-gradient(43deg, #405de6 0%, #5851d8 17%, #833ab4 37%, #c13584 49%, #e1306c 72%, #e1306c 88%, #ee8bac 97%, #ffdc80 100%), var(--bs-red);margin-right:10px;margin-bottom:10px;" href = "{% url 'view_all_doctors' %}">Doctor Manager</a> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </article>
        </div>
        <div class = "col-md-6">
            <lottie-player src="https://assets10.lottiefiles.com/packages/lf20_wdXBRc.json"  background="transparent"  speed="1"  style="width: auto; height: auto;"  loop  autoplay></lottie-player>
        </div>
    </div>
</div>
{% endblock %}

Service/templates/Service/relateddoctors.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class = "container">
    <h1 class = "text-center">Doctor{{Doctors.count|pluralize}} of {{Hospital.Hospital_Name}}</h1>
    <hr/>
    <div class="row">
        {% for doctor in Doctors %}
        <div class="col-md-4" style = "margin-bottom:10px;">
            <div class="card" style="width: auto;">
                {% if doctor.Profile_Picture %}
                    <img src="{{doctor.Profile_Picture.url}}" class="card-img-top" alt="{% static 'default.png' %}">
                {% else %}
                    <img src="{% static 'default.png' %}" class="card-img-top" alt="{% static 'default.png' %}">
                {% endif %}
                <div class="card-body">
                    <h1 class="card-subtitle mb-2" style="font-size: 20px;">Name : Dr. {{doctor.Doctor_Name}}</h1>
                    <h1 style="font-size: 18px;">Qualification : {{doctor.Qualification}}</h1>
                    <h1 style="font-size: 18px;">Specialization: {% if doctor.Specialization %} {{doctor.Specialization}} {% else %}-{% endif %}</h1>
                    <h1 style="font-size: 18px;">Date of Joining : {{doctor.Date_of_Joining}}</h1>
                    <h1 style="font-size: 18px;">Hospital : {{doctor.Hospital.Hospital_Name}}</h1>
                    <h1 style="font-size: 18px;">Hospital Code : {{doctor.Hospital.Hospital_Code}}</h1>
                    <h1 style="font-size: 18px;">Hospital Location : <i class="{{ doctor.Hospital.Location.flag_css }}"></i> {{doctor.Hospital.Location.name}}</h1>
                    <div class = "d-inline-block py-2">
                        <form method = "POST" action = "{% url 'delete_doctor_profile' doctor.id doctor.slug %}">
                        <a class="btn btn-outline-success" href = "{% url 'update_doctor_details' doctor.id doctor.slug %}"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none">
                                <path d="M4 16L4 17C4 18.6569 5.34315 20 7 20L17 20C18.6569 20 20 18.6569 20 17L20 16M16 8L12 4M12 4L8 8M12 4L12 16" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                            </svg>&nbsp;Update
                        </a>
                            {% csrf_token %}
                            <button type = "submit" class="btn btn-outline-danger">
                                <i class="icon ion-android-delete"></i>&nbsp;Delete
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class = "d-inline-block">
        <a class="btn btn-primary" href = "{% url 'add_doctor' %}" style="background: linear-gradient(43deg, #405de6 0%, #5851d8 17%, #833ab4 37%, #c13584 49%, #e1306c 72%, #e1306c 88%, #ee8bac 97%, #ffdc80 100%), var(--bs-red);"><i class = "fa fa-plus"></i> Add a Doctor</a>
    </div>
</div>
{% endblock %}

content_manager/templates/messages.html
{% for message in messages %}
{% if forloop.last %}
<div class="container-fluid py-2" id = 'message' style = "display:none;">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close" id = "custom">
    </button>
    <div class = "text-center">
      {{message}}
    </div>
  </div>
</div>
{% endif %}
{% endfor %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
{% for message in messages %}
<script>
$(message)
    .css('opacity', 0)
    .slideDown('slow')
    .animate(
      { opacity: 1 },
      { queue: false, duration: 'slow' }
);
$('.alert').click(function(){
$(message)
  $(message).animate({height:0, opacity: 0}, 2000);
});
 window.setTimeout(function() {
      $("#message").slideUp(500, function() {
          $(this).remove();
      });
  }, 6000);
</script>
{% endfor %}